services:
#    utilisateur.example:
#        class: UtilisateurBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.form.type.utilisateur.edit:
        class: UtilisateurBundle\Form\UtilisateurEditType
        arguments: ['@otacos_app.service']
        tags:
            - { name: form.type }
