<?php

namespace TracabiliteBundle\Repository;

/**
 * ElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementRepository extends \Doctrine\ORM\EntityRepository
{
	public function getElementByCategorie($categ){
		return $this->createQueryBuilder('e')
			->join('e.categorie', 'c')
			->addSelect('c')
			->andWhere('c.slug = :slugCategorie')
			->setParameter('slugCategorie', $categ->getSlug())
            ->getQuery()->getResult();
	}
}
