<?php

namespace TracabiliteBundle\Repository;
use Doctrine\ORM\Query\ResultSetMapping;
/**
 * TraceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraceRepository extends \Doctrine\ORM\EntityRepository
{
	public function getDuJour(){
		return $this->createQueryBuilder('t')
			->join('t.element', 'e')
			->select('e.id')
			->andWhere('t.date = :date')
			->setParameter('date', date("Y-m-d") )
            ->getQuery()->getScalarResult();
	}

	public function getNbrTraceDuJour(){
		$rsm = new ResultSetMapping();
		$rsm->addScalarResult('nbr', 'nbr');
        $rsm->addScalarResult('categId', 'categId');

		$sql = "SELECT count(e.id) nbr, c.id categId from categorie c
			LEFT JOIN element e ON c.id = e.categorie_id
			JOIN trace t ON e.id = t.element_id group by c.id";

		//$em = $this->getDoctrine()->getManager();

		$query = $this->_em->createNativeQuery($sql, $rsm);

        return $caResults = $query->getScalarResult();


		/*return $this->createQueryBuilder('t')
			->join('t.element', 'e')
			->join('e.categorie', 'c')
			->select('count(c.id) nbr, c.id')
			->andWhere('t.date = :date')
			->setParameter('date', date("Y-m-d") )
			->groupBy('c.id')
            ->getQuery()->getScalarResult();*/
	}

	public function getDuJourBySlugElement($slug){
		$res = $this->createQueryBuilder('t')
			->join('t.element', 'e')
			//->select('e.id')
			->andWhere('e.slug = :slug')
			->setParameter('slug', $slug )
			->andWhere('t.date = :date')
			->setParameter('date', date("Y-m-d") )
            ->getQuery()->getResult();

        if(count($res) > 0){
        	return $res[0];
        }
        return null;
	}
}
