<?php

namespace TracabiliteBundle\Repository;
use Doctrine\ORM\Query\ResultSetMapping;
/**
 * TraceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraceRepository extends \Doctrine\ORM\EntityRepository
{
	public function getDuJour(){
		return $this->createQueryBuilder('t')
			->join('t.element', 'e')
			->select('e.id')
			->andWhere('t.date = :date')
			->setParameter('date', date("Y-m-d") )
            ->getQuery()->getScalarResult();
	}

	public function getNbrTraceDuJour(){
		$rsm = new ResultSetMapping();
		$rsm->addScalarResult('nbr', 'nbr');
		$rsm->addScalarResult('qte', 'qte');
		$rsm->addScalarResult('prcent', 'prcent');
        $rsm->addScalarResult('categId', 'categId');

		$sql = "SELECT tqte.categId, coalesce(tnbr.nbr,0) as nbr, tqte.qte, coalesce(  TRUNCATE(sum((tnbr.nbr/tqte.qte)*100),0)   , 0) as prcent From

			(SELECT count(e.id) qte, c.id categId from categorie c
						LEFT JOIN element e ON c.id = e.categorie_id
						LEFT JOIN trace t ON e.id = t.element_id group by c.id ) tqte LEFT JOIN
			            
			(SELECT count(t.id) nbr, c.id categId from categorie c
						LEFT JOIN element e ON c.id = e.categorie_id
						LEFT JOIN trace t ON e.id = t.element_id 
						where t.date = '".date("Y-m-d")."'
						group by c.id) tnbr
			ON tnbr.categId = tqte.categId
			group by tqte.categId";

			//echo($sql);die();

		//$em = $this->getDoctrine()->getManager();

		$query = $this->_em->createNativeQuery($sql, $rsm);

        return $caResults = $query->getScalarResult();


		/*return $this->createQueryBuilder('t')
			->join('t.element', 'e')
			->join('e.categorie', 'c')
			->select('count(c.id) nbr, c.id')
			->andWhere('t.date = :date')
			->setParameter('date', date("Y-m-d") )
			->groupBy('c.id')
            ->getQuery()->getScalarResult();*/
	}

	public function getAllArray($entreprise){
		return $res = $this->createQueryBuilder('t')
		->andWhere('t.entreprise = :entreprise')->setParameter('entreprise', $entreprise )
		->join('t.element', 'e')
		->addSelect('e')
		->leftJoin('t.photos', 'p')
		->addSelect('p')
		->getQuery()->getArrayResult();
	}

	public function getDuJourBySlugElement($slug){
		$res = $this->createQueryBuilder('t')
			->join('t.element', 'e')
			//->select('e.id')
			
			->andWhere('t.date = :date')
			->setParameter('date', date("Y-m-d") )
            ->getQuery()->getResult();

        if(count($res) > 0){
        	return $res[0];
        }
        return null;
	}
}
