releve_show:
    path:     /{id}/show
    defaults: { _controller: "TemperatureBundle:Releve:show" }
    methods:  GET

releve_new:
    path:     /new
    defaults: { _controller: "TemperatureBundle:Releve:new" }
    methods:  [GET, POST]

releve_edit:
    path:     /{id}/edit
    defaults: { _controller: "TemperatureBundle:Releve:edit" }
    methods:  [GET, POST]

releve_delete:
    path:     /{id}/delete
    defaults: { _controller: "TemperatureBundle:Releve:delete" }
    methods:  DELETE
