<?php

namespace ReceptionBundle\Repository;

/**
 * ReceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceptionRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCategValidDuJour($categorie, $entreprise){
		$res = $this->createQueryBuilder('r')
			//->join('r.categorie', 'c')
			//->select('e.id')
			->andWhere('r.categorie = :categorie')
			->setParameter('categorie', $categorie )
			->andWhere('r.date = :date')
			->setParameter('date', date("Y-m-d") )
            ->getQuery()->getScalarResult();

        return $res;
	}


	/*public function getDuJourByCateg($categorie){
		$res = $this->createQueryBuilder('r')
			//->join('r.categorie', 'c')
			//->select('e.id')
			->andWhere('r.categorie = :categorie')
			->setParameter('categorie', $categorie )
			->andWhere('r.date = :date')
			->setParameter('date', date("Y-m-d") )
            ->getQuery()->getResult();

        if(count($res) > 0){
        	return $res[0];
        }
        return null;
	}*/

	public function getAllArray($entreprise){
		return $res = $this->createQueryBuilder('r')
		->andWhere('r.entreprise = :entreprise')->setParameter('entreprise', $entreprise )
		->join('r.categorie', 'c')
		->addSelect('c')
		->leftJoin('r.photos', 'p')
		->addSelect('p')
		->getQuery()->getArrayResult();
	}
}
