app_accueil:
    resource: "@AppBundle/Resources/config/routing.yml"

entreprise:
    resource: "@EntrepriseBundle/Resources/config/routing.yml"
    prefix:   /entreprise

utilisateur:
    resource: "@UtilisateurBundle/Resources/config/routing.yml"
    prefix:   /utilisateur

temperature:
    resource: "@TemperatureBundle/Resources/config/routing.yml"
    prefix:   /temperature

archives:
    resource: "@TracabiliteBundle/Resources/config/routing.yml"
    prefix:   /tracabilite

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

reception:
    resource: "@ReceptionBundle/Resources/config/routing.yml"
    prefix:   /reception
