temperature:
    resource: "@TemperatureBundle/Resources/config/routing.yml"
    prefix:   /temperature

app_accueil:
    resource: "@AppBundle/Resources/config/routing.yml"

archives:
    resource: "@TracabiliteBundle/Resources/config/routing.yml"
    prefix:   /tracabilite

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
