temperature_index:
    path:     /
    defaults: { _controller: TemperatureBundle:Temperature:index }

temperature_releve_choix_moment:
    path:     nouveau/{slugCategorie}/
    defaults: { _controller: TemperatureBundle:Temperature:choixMoment }

temperature_releve_new:
    path:     nouveau/{slugCategorie}/{moment}
    defaults: { _controller: TemperatureBundle:Releve:new }
