<?php

namespace UtilisateurBundle\Repository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * EntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNbr(){

		$rsm = new ResultSetMapping();
		$rsm->addScalarResult('nbr', 'nbr');
		$rsm->addScalarResult('numRes', 'numRes');

		$sql = "SELECT count(*) as nbr, 1 as numRes from utilisateur 
		union SELECT count(*) as nbr, 2 as numRes from utilisateur where roles like '%ROLE_ADMIN%' or roles like '%ROLE_SUPER_ADMIN%' 
		union SELECT count(*) as nbr, 3 as numRes from utilisateur where roles like '%ROLE_CHEF_ENTREPRISE%' ";

		$query = $this->_em->createNativeQuery($sql, $rsm);

        $result = $query->getScalarResult();

        $keyRes = array(1=>'total', 2=>'admin', 3=>'chefEntreprise');
        $aRetourner = null;
        foreach ($result as $r) {
        	$aRetourner[ $keyRes[ $r['numRes'] ] ] = $r['nbr'];
        }
        return $aRetourner;
	}
}
