<?php

namespace TemperatureBundle\Repository;

/**
 * DegreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DegreRepository extends \Doctrine\ORM\EntityRepository
{
}
