<?php

namespace TemperatureBundle\Repository;

/**
 * ReleveEquipementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReleveEquipementRepository extends \Doctrine\ORM\EntityRepository
{
}
