<?php

namespace TemperatureBundle\Repository;

/**
 * ReleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReleveRepository extends \Doctrine\ORM\EntityRepository
{
}
